import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import ReduxProvider from '@/redux/provider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-200 dark:bg-slate-800">
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html >
  )
}
